title: "dasfef"
tagline: "자신을 자랑하지 마라"
description: "남들보다 늦은 나이에 개발자로의 꿈을 펼칩니다. 함께 어둠의 심연에서 발버둥치길 바라며"
github_username: dasfef
baseurl: ""
url: "https://dasfef.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: tareqdandachi/jekyll-shell-theme

# github_username: @dasfef

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - posts.md
  - portfolio.md
  - about.md

# set the size of the text to 'large' or 'small', default is small
font-size: small

google-site-verification: gAYUGzS0v-aNZWTuMGUgQ5n24TZ2wTgS7O91XaXGobA
naver-site-verification: bc018644a935e2b6c87f343b01b200a4f6e55bf9